### ISSUE TITLE
Can't delete my own comments

### ISSUE THREAD

**Issue by nstoeckigt** [wekan/univention#10]
I tried to remove one of my Comments via the `remove` Link but nothing happens but the unterline of the Link disappeared.

Environment:
UCS: 4.4-4 errata528
Installed: wekan=3.89

I found the following Traceback in the wekan log
<pre>
----- 8< -----
 Exception in removedobserveChanges callback: Error: Removed nonexistent
document bJYbKPvBjkNcJ7ii9
     at SessionCollectionView.removed (packages/ddp-
server/livedata_server.js:202:17)
     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
     at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
     at Subscription.subscriptionProto.<computed> [as removed]
(packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
     at removed (packages/cottz:publish-
relations/lib/server/cursor/cursor.js:52:13)
     at runWithEnvironment (packages/meteor.js:1286:24)
     at packages/meteor.js:1299:14
     at packages/mongo/observe_multiplex.js:178:30
     at Array.forEach (<anonymous>)
     at Function._.each._.forEach (packages/underscore.js:139:11)
     at Object.task (packages/mongo/observe_multiplex.js:172:9)
     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
     at packages/meteor.js:894:12
 Exception in removedobserveChanges callback: Error: Removed nonexistent
document bJYbKPvBjkNcJ7ii9
     at SessionCollectionView.removed (packages/ddp-
server/livedata_server.js:202:17)
     at Session.removed (packages/ddp-server/livedata_server.js:394:10)
     at Subscription.removed (packages/ddp-server/livedata_server.js:1298:19)
     at Subscription.subscriptionProto.<computed> [as removed]
(packages/mdg:meteor-apm-agent/lib/hijack/wrap_subscription.js:89:30)
     at removed (packages/cottz:publish-
relations/lib/server/cursor/cursor.js:52:13)
     at runWithEnvironment (packages/meteor.js:1286:24)
     at packages/meteor.js:1299:14
     at packages/mongo/observe_multiplex.js:178:30
     at Array.forEach (<anonymous>)
     at Function._.each._.forEach (packages/underscore.js:139:11)
     at Object.task (packages/mongo/observe_multiplex.js:172:9)
     at Meteor._SynchronousQueue.SQp._run (packages/meteor.js:917:16)
     at packages/meteor.js:894:12
----- >8 -----
</pre>

**Comment by xet7** [comment]
Wekan v3.97 for Univention has now been released, it includes fix to this.
