### ISSUE TITLE
Can't edit own comments

### ISSUE THREAD

**Issue by nstoeckigt** [wekan/univention#9]
When trying to edit one of my own comments the changes I made aren't saved but silently discarded.

Environment:
UCS: 4.4-4 errata528
Installed: wekan=3.89

I found the following Traceback in the wekan log:
<pre>
----- 8< -----
 Exception from sub board id EEsCYwxekPGFbdvQK Error: Match error: Expected
boolean, got undefined
     at check (packages/check/match.js:36:17)
     at CursorMethods.<anonymous> (server/publications/boards.js:73:3)
     at Subscription.<anonymous> (packages/cottz:publish-
relations/lib/server/publish_relations.js:13:23)
     at packages/matb33_collection-hooks.js:347:24
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Subscription._handler (packages/matb33_collection-hooks.js:346:28)
     at packages/check/match.js:118:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._failIfArgumentsAreNotAllChecked
(packages/check/match.js:116:43)
     at maybeAuditArgumentChecks (packages/ddp-
server/livedata_server.js:1768:18)
     at packages/ddp-server/livedata_server.js:1046:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Subscription._runHandler (packages/ddp-
server/livedata_server.js:1044:51)
     at Subscription.MeteorX.Subscription._runHandler
(packages/lamhieu_unblock.js:68:22)
     at Subscription.subscriptionProto._runHandler (packages/mdg:meteor-apm-
agent/lib/hijack/wrap_subscription.js:12:24)
     at Session.MeteorX.Session._startSubscription
(packages/lamhieu_unblock.js:56:7)
     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
     at Session.MeteorX.Session.protocol_handlers.sub
(packages/lamhieu_unblock.js:27:15)
     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:77:34
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Session.sessionProto.protocol_handlers.sub (packages/mdg:meteor-apm-
agent/lib/hijack/wrap_session.js:76:44)
     at packages/ddp-server/livedata_server.js:559:43
 Sanitized and reported to the client as: errorClass [Error]: Match failed
[400]
     at errorClass.<anonymous> (packages/check/match.js:91:27)
     at new errorClass (packages/meteor.js:655:17)
     at check (packages/check/match.js:36:17)
     at CursorMethods.<anonymous> (server/publications/boards.js:73:3)
     at Subscription.<anonymous> (packages/cottz:publish-
relations/lib/server/publish_relations.js:13:23)
     at packages/matb33_collection-hooks.js:347:24
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Subscription._handler (packages/matb33_collection-hooks.js:346:28)
     at packages/check/match.js:118:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Object._failIfArgumentsAreNotAllChecked
(packages/check/match.js:116:43)
     at maybeAuditArgumentChecks (packages/ddp-
server/livedata_server.js:1768:18)
     at packages/ddp-server/livedata_server.js:1046:15
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Subscription._runHandler (packages/ddp-
server/livedata_server.js:1044:51)
     at Subscription.MeteorX.Subscription._runHandler
(packages/lamhieu_unblock.js:68:22)
     at Subscription.subscriptionProto._runHandler (packages/mdg:meteor-apm-
agent/lib/hijack/wrap_subscription.js:12:24)
     at Session.MeteorX.Session._startSubscription
(packages/lamhieu_unblock.js:56:7)
     at Session.sub (packages/ddp-server/livedata_server.js:625:12)
     at Session.MeteorX.Session.protocol_handlers.sub
(packages/lamhieu_unblock.js:27:15)
     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:77:34
     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
     at Session.sessionProto.protocol_handlers.sub (packages/mdg:meteor-apm-
agent/lib/hijack/wrap_session.js:76:44)
     at packages/ddp-server/livedata_server.js:559:43 {
   isClientSafe: true,
   error: 400,
   reason: 'Match failed',
   details: undefined,
   message: 'Match failed [400]',
   errorType: 'Meteor.Error'
 }
----- >8 -----
</pre>

**Comment by xet7** [comment]
@nstoeckigt 

This is already fixed in Wekan v3.97 that will be released to Univention soon.

**Comment by xet7** [comment]
Wekan v3.97 for Univention has now been released, it includes fix to this.
